config/routes.rb
Rails.application.routes.draw do
  resources :messages

  root 'messages#index'


end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def edit
    @message = Message.find(params[:id])
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      redirect_to messages_path
    end
  end

  def update
    @message = Message.find(params[:id])

    if @message.update(message_params)
      redirect_to messages_path
    end
  end

  private
  def message_params
    params.require(:message).permit(:author, :message, :anonymous, :image_pick, :title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Happy Valentine's Day!</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class= "container">


<%= yield %>

</div>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message, html: {class: 'form-horizontal'}) do |f| %>

  <div class="form-group">
      <%= f.label :title, class: "col-md-1" %>
      <%= f.text_field :title, class: "col-md-3" %>
  </div>

  <div class="form-group">
    <%= f.label :author, class: "col-md-1" %>
    <%= f.text_field :author, class: "col-md-3" %>
  </div>

  <div class="form-group">
    <%= f.label :message, class: "col-md-1" %>
    <%= f.text_field :message, class: "col-md-3 message_text" %>
  </div>

<br />
<br />

  <div class="form-group">
    <div class="col-md-offset-1">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to 'cancel', messages_path, class: "btn btn-default" %>
    </div>
  </div>

</form>


<% end %>

app/views/messages/edit.html.erb
<div class="page-header">

  <h1>Edit <%= @message.title %></h1>
</div>
<br />
<br />

<%= render 'form' %>

app/views/messages/index.html.erb
<div class= "jumbotron">
  <h1>Valentine's Day!</h1>
  <p>"A quote about love"</p>
  <p>Pete Vliet</p>

</div>
<br />

<p>
  <%= link_to 'New Message', new_message_path, class: 'btn btn-danger' %>
</p>

<br />
<br />

<table class= "table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Anonymous?</th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
    <tr>
      <td><%= link_to message.title, message %></td>
      <td><%= message.author %></td>
      <td><%= message.anonymous %></td>
      <td class="text-right">
        <%= link_to 'edit', edit_message_path(message), class: 'btn btn-info' %>
      </td>
    </tr>
    <% end %>

  </tbody>


</table>

<br />
<br />
<%= image_tag 'choo.jpg', class: "img" %>

app/views/messages/new.html.erb
<div class="page-header">

  <h1>New Valentine's Message</h1>
</div>
<br />
<br />

<%= render 'form' %>

app/views/messages/show.html.erb
<div class="page-header">
  <h1><%= @message.title %> </h1>
</div>
<br />
<br />

<dl class="dl-horizontal">
  <dt>From:  </dt>  <dr>  <%= @message.author %></dr><br />
  <dt>Message:  </dt>  <dr>  <%= @message.message %></dr><br />

</dl>

<br />
<br />

<%= link_to 'back', messages_path, class: 'btn btn-default' %>
<%= link_to 'edit', edit_message_path(@message), class: 'btn btn-info' %>